// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColType } from "./ColType";
import type { ParameterOptionDisplayDetails } from "./ParameterOptionDisplayDetails";

export interface ColumnOptions {
  allowedColumnTypes: Array<ColType> | null;
  fromDataset: string;
  displayDetails: ParameterOptionDisplayDetails;
}
