// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterOptionDisplayDetails } from "./ParameterOptionDisplayDetails";

export interface NumericIntOptions { range: Array<number> | null, default: number | null, displayDetails: ParameterOptionDisplayDetails, }