// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecParameterValue } from "./SpecParameterValue";

export interface SpecParameter {
  name: string;
  parameter: SpecParameterValue;
}
