plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  "@uiw/react-md-editor@*":
    dependencies:
      "@mapbox/rehype-prism": "*"
  "@deck.gl/layers@*":
    dependencies:
      "@luma.gl/core": "*"
      "@math.gl/web-mercator": "*"
      "math.gl": "*"
  "react-vega@*":
    dependencies:
      "prop-types": "*"
  "styled-components@*":
    dependencies:
      "react-is": "*"

nodeLinker: node-modules
