nodeLinker: node-modules

packageExtensions:
  "@deck.gl/layers@*":
    dependencies:
      "@luma.gl/core": "*"
      "@math.gl/web-mercator": "*"
      math.gl: "*"
  "@uiw/react-md-editor@*":
    dependencies:
      "@mapbox/rehype-prism": "*"
  react-vega@*:
    dependencies:
      prop-types: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: "https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js"

yarnPath: ".yarn/releases/yarn-berry.cjs"
