[workspace]

members = [
  "matico_spec_derive",
  "matico_spec",
  "matico_server",
  "matico_compute/matico_area_analysis",
  "matico_compute/matico_analysis",
  "matico_compute/matico_dot_density_analysis",
]
