// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregationSummary } from "./AggregationSummary";

export interface AggregateStep {
  groupByColumns: Array<string>;
  aggregate: Array<AggregationSummary>;
}
