// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregationType } from "./AggregationType";

export interface AggregationSummary { column: string, aggType: AggregationType, rename: string | null, }