// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dataset } from "./Dataset";
import type { DatasetTransform } from "./DatasetTransform";
import type { Metadata } from "./Metadata";
import type { Page } from "./Page";
import type { Pane } from "./Pane";
import type { Theme } from "./Theme";

export interface App { pages: Array<Page>, panes: Array<Pane>, datasets: Array<Dataset>, datasetTransforms: Array<DatasetTransform>, theme: Theme | null, metadata: Metadata, }