// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetRef } from "./DatasetRef";

export interface CategorySelectorPane {
  column: string;
  dataset: DatasetRef;
  id: string;
  label: string | null;
  name: string;
}
