// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateOpts } from "./DateOpts";
import type { FloatOpts } from "./FloatOpts";
import type { IntOpts } from "./IntOpts";
import type { StringOpts } from "./StringOpts";

export type ChangeType =
  | ({ type: "date" } & DateOpts)
  | ({ type: "string" } & StringOpts)
  | ({ type: "int" } & IntOpts)
  | ({ type: "float" } & FloatOpts);
