// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColorSpecification =
  | { rgba: Array<number> }
  | { rgb: Array<number> }
  | { named: string }
  | { hex: string };
