// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnTransform } from "./ColumnTransform";

export interface ColumnTransformStep {
  transforms: Array<ColumnTransform>;
}
