// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";

export type ColumnTransformOp = { type: "changeType" } & ChangeType | { type: "rename" } & string | { type: "drop" };