// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";
import type { Rename } from "./Rename";

export type ColumnTransform = { type: "changeType" } & ChangeType | { type: "rename" } & Rename | { type: "drop" };