// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeType } from "./ChangeType";

export interface ColumnTransform {
  column: string;
  to: ChangeType;
}
