// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";

export interface ControlsPane {
  name: string;
  id: string;
  title: string;
  controls: Array<Control>;
}
