// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeControl } from "./RangeControl";
import type { SelectControl } from "./SelectControl";

export type Control =
  | ({ type: "select" } & SelectControl)
  | ({ type: "range" } & RangeControl);
