// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layout } from "./Layout";
import type { PaneRef } from "./PaneRef";

export interface ContainerPane {
  name: string;
  id: string;
  layout: Layout;
  panes: Array<PaneRef>;
}
