// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetMetric } from "./DatasetMetric";
import type { Filter } from "./Filter";

export interface DatasetVal {
  dataset: string;
  column: string | null;
  metric: DatasetMetric | null;
  filters: Array<Filter> | null;
  featureId: string | null;
}
