// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetTransformStep } from "./DatasetTransformStep";

export interface DatasetTransform { id: string, name: string, description: string, sourceId: string, steps: Array<DatasetTransformStep>, }