// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregateStep } from "./AggregateStep";
import type { ColumnTransformStep } from "./ColumnTransformStep";
import type { FilterStep } from "./FilterStep";
import type { JoinStep } from "./JoinStep";
import type { WASMCompute } from "./WASMCompute";

export type DatasetTransformStep =
  | ({ type: "filter" } & FilterStep)
  | ({ type: "aggregate" } & AggregateStep)
  | ({ type: "join" } & JoinStep)
  | ({ type: "compute" } & WASMCompute)
  | ({ type: "columnTransformStep" } & ColumnTransformStep);
