// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

export interface DatasetRef {
  name: string;
  filters: Array<Filter> | null;
}
