// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VarOr } from "./VarOr";

export interface DateFilter {
  variable: string;
  min: VarOr<string> | null;
  max: VarOr<string> | null;
}
