// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetRef } from "./DatasetRef";
import type { VarOr } from "./VarOr";

export interface DateTimeSliderPane { column: string, dataset: DatasetRef, id: string, label: string | null, max: VarOr<string>, min: VarOr<string>, name: string, }