// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingType } from "./MappingType";
import type { VarOr } from "./VarOr";

export interface Domain<D> {
  type: MappingType;
  values: VarOr<Array<D>>;
}
