// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSpecification } from "./ColorSpecification";
import type { DatasetRef } from "./DatasetRef";
import type { Labels } from "./Labels";
import type { MappingVarOr } from "./MappingVarOr";

export interface HistogramPane { name: string, id: string, dataset: DatasetRef, column: string, color: MappingVarOr<ColorSpecification> | null, maxbins: number | null, labels: Labels | null, }