// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImputeMethod } from "./ImputeMethod";

export interface ImputeStep { column: string, method: ImputeMethod, }