// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImputeMethod = { type: "value", value: number } | { type: "mean" } | { type: "median" };