// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JoinType } from "./JoinType";

export interface JoinStep { otherSourceId: string, joinType: JoinType, joinColumnsLeft: Array<string>, joinColumnsRight: Array<string>, }