// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Justification = "flex-start" | "flex-end" | "center" | "space-between" | "space-around" | "space-evenly";