// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Labels {
  title: string | null;
  subTitle: string | null;
  attribution: string | null;
  xLabel: string | null;
  yLabel: string | null;
}
