// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatasetRef } from "./DatasetRef";
import type { LayerStyle } from "./LayerStyle";
import type { TooltipColumnSpec } from "./TooltipColumnSpec";

export interface Layer { name: string, id: string, source: DatasetRef, style: LayerStyle, tooltipColumns: Array<TooltipColumnSpec> | null, }