// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreeLayout } from "./FreeLayout";
import type { GridLayout } from "./GridLayout";
import type { LinearLayout } from "./LinearLayout";
import type { TabLayout } from "./TabLayout";

export type Layout = { type: "free" } & FreeLayout | { type: "linear" } & LinearLayout | { type: "grid" } & GridLayout | { type: "tabs" } & TabLayout;