// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alignment } from "./Alignment";
import type { GapSize } from "./GapSize";
import type { Justification } from "./Justification";
import type { LinearLayoutDirection } from "./LinearLayoutDirection";

export interface LinearLayout { direction: LinearLayoutDirection, allowOverflow: boolean, justify: Justification, gap: GapSize | null, align: Alignment, }