// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinearLayoutDirection } from "./LinearLayoutDirection";

export interface LinearLayout { direction: LinearLayoutDirection, allowOverflow: boolean, }