// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Range } from "./Range";
import type { VarOr } from "./VarOr";

export interface Mapping<D, R> { variable: string, domain: VarOr<Array<D>>, range: VarOr<Range<R>>, }