// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Domain } from "./Domain";
import type { Range } from "./Range";

export interface Mapping<D, R> {
  variable: string;
  domain: Domain<D>;
  range: Range<R>;
}
