// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainVal } from "./DomainVal";
import type { Mapping } from "./Mapping";
import type { Variable } from "./Variable";

export type MappingVarOr<T> = Variable | Mapping<DomainVal, T> | T;
