// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseMap } from "./BaseMap";
import type { Layer } from "./Layer";
import type { MapControls } from "./MapControls";
import type { SelectionOptions } from "./SelectionOptions";
import type { VarOr } from "./VarOr";
import type { View } from "./View";

export interface MapPane { name: string, id: string, view: VarOr<View>, layers: Array<Layer>, baseMap: BaseMap | null, selectionOptions: SelectionOptions | null, controls: MapControls | null, }