// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapProjection = "geoConicConformal" | "geoTransverseMercator" | "geoNaturalEarth1" | "geoConicEquidistant" | "geoOrthographic" | "geoStereographic" | "geoMercator" | "geoEquirectangular";