// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecParameter } from "./SpecParameter";

export interface MaticoApiDataset { name: string, description: string, serverUrl: string, apiId: string | null, params: Array<SpecParameter>, }