// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterValue } from "./ParameterValue";

export interface OptionGroupVal { name: string, parameter: ParameterValue, }