// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Layout } from "./Layout";
import type { PaneRef } from "./PaneRef";

export interface Page { name: string, id: string, icon: string | null, panes: Array<PaneRef>, path: string | null, layout: Layout, }