// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerPane } from "./ContainerPane";
import type { ControlsPane } from "./ControlsPane";
import type { HistogramPane } from "./HistogramPane";
import type { MapPane } from "./MapPane";
import type { PieChartPane } from "./PieChartPane";
import type { ScatterplotPane } from "./ScatterplotPane";
import type { StaticMapPane } from "./StaticMapPane";
import type { TextPane } from "./TextPane";

export type Pane = { type: "map" } & MapPane | { type: "staticMap" } & StaticMapPane | { type: "text" } & TextPane | { type: "container" } & ContainerPane | { type: "histogram" } & HistogramPane | { type: "scatterplot" } & ScatterplotPane | { type: "pieChart" } & PieChartPane | { type: "controls" } & ControlsPane;