// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnOptions } from "./ColumnOptions";
import type { NumericCategoryOptions } from "./NumericCategoryOptions";
import type { NumericFloatOptions } from "./NumericFloatOptions";
import type { NumericIntOptions } from "./NumericIntOptions";
import type { OptionGroup } from "./OptionGroup";
import type { RepeatedOption } from "./RepeatedOption";
import type { TableOptions } from "./TableOptions";
import type { TextCategoryOptions } from "./TextCategoryOptions";
import type { TextOptions } from "./TextOptions";

export type ParameterOptions = { type: "optionGroup" } & OptionGroup | { type: "repeatedOption" } & RepeatedOption | { type: "numericFloat" } & NumericFloatOptions | { type: "numericInt" } & NumericIntOptions | { type: "numericCategory" } & NumericCategoryOptions | { type: "textCategory" } & TextCategoryOptions | { type: "column" } & ColumnOptions | { type: "table" } & TableOptions | { type: "text" } & TextOptions;