// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VarOr } from "./VarOr";

export interface RangeFilter { variable: string, min: VarOr<number> | null, max: VarOr<number> | null, }