// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterOptionDisplayDetails } from "./ParameterOptionDisplayDetails";
import type { ParameterOptions } from "./ParameterOptions";

export interface RepeatedOption { options: ParameterOptions, displayDetails: ParameterOptionDisplayDetails, minTimes: number, maxTimes: number | null, }