// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectionMode } from "./SelectionMode";

export interface SelectionOptions {
  selectionEnabled: boolean;
  selectionMode: SelectionMode;
}
