// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregationType } from "./AggregationType";
import type { SummaryStyle } from "./SummaryStyle";

export interface SummaryItem { name: string, dataset: string, column: string, summaryTypes: Array<AggregationType>, groupbyColumns: Array<string>, style: SummaryStyle, }