// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InitalSelection } from "./InitalSelection";
import type { Orientation } from "./Orientation";

export interface SwitchesPane {
  id: string;
  label: string | null;
  options: Array<string>;
  description: string | null;
  initalSelection: InitalSelection;
  orientation: Orientation;
  name: string;
}
