// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterOptionDisplayDetails } from "./ParameterOptionDisplayDetails";

export interface TextOptions {
  maxLength: number | null;
  displayDetails: ParameterOptionDisplayDetails;
  default: string | null;
}
