// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TextPane {
  name: string;
  id: string;
  content: string;
  font: string | null;
  background: string | null;
}
