// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorSpecification } from "./ColorSpecification";

export interface Theme {
  primaryColor: ColorSpecification | null;
  secondaryColor: ColorSpecification | null;
  logoUrl: string | null;
}
