// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerContentType } from "./LayerContentType";

export interface TiledLayer { urlTemplate: string, layerContentType: LayerContentType, }