// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Variable {
  varId: string;
  property: string | null;
  bind: boolean | null;
}
