// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface View { lat: number, lng: number, zoom: number, bearing: number, pitch: number, }