// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecParameter } from "./SpecParameter";

export interface WASMCompute { name: string, url: string, params: Array<SpecParameter>, }