// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface App {
  id: string;
  name: string;
  owner_id: string;
  description: string;
  spec: AppSpec;
  created_at: string;
  updated_at: string;
  public: boolean;
}
