// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CreateAppDTO { name: string, owner_id: string, description: string, spec: AppSpec, public: boolean, }