// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HistogramParams {
  treatNullAsZero: boolean | null;
  inclusiveBins: boolean | null;
  noBins: number;
  binEdges: Array<number> | null;
}
