// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HistogramEntry { binStart: number, binEnd: number, binMid: number, freq: number, }