// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LogorithmicParams {
  noBins: number;
  base: number | null;
  treatNullAsZero: boolean | null;
}
