// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicStatsResults } from "./BasicStatsResults";
import type { HistogramResults } from "./HistogramResults";
import type { JenksResults } from "./JenksResults";
import type { LogorithmicParams } from "./LogorithmicParams";
import type { QuantileResults } from "./QuantileResults";
import type { ValueCountsResults } from "./ValueCountsResults";

export type StatResults = { quantiles: QuantileResults } | { jenks: JenksResults } | { logotithmic: LogorithmicParams } | { basicStats: BasicStatsResults } | { valueCounts: ValueCountsResults } | { histogram: HistogramResults };