// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface User { id: string, username: string, email: string, created_at: string, updated_at: string, }