/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_view_free(a: number): void;
export function __wbg_get_view_lat(a: number): number;
export function __wbg_set_view_lat(a: number, b: number): void;
export function __wbg_get_view_lng(a: number): number;
export function __wbg_set_view_lng(a: number, b: number): void;
export function __wbg_get_view_zoom(a: number): number;
export function __wbg_set_view_zoom(a: number, b: number): void;
export function __wbg_get_view_bearing(a: number): number;
export function __wbg_set_view_bearing(a: number, b: number): void;
export function __wbg_get_view_pitch(a: number): number;
export function __wbg_set_view_pitch(a: number, b: number): void;
export function __wbg_mapcontrols_free(a: number): void;
export function __wbg_get_mapcontrols_scale(a: number): number;
export function __wbg_set_mapcontrols_scale(a: number, b: number): void;
export function __wbg_get_mapcontrols_geolocate(a: number): number;
export function __wbg_set_mapcontrols_geolocate(a: number, b: number): void;
export function __wbg_get_mapcontrols_navigation(a: number): number;
export function __wbg_set_mapcontrols_navigation(a: number, b: number): void;
export function __wbg_get_mapcontrols_fullscreen(a: number): number;
export function __wbg_set_mapcontrols_fullscreen(a: number, b: number): void;
export function __wbg_get_selectionoptions_selection_enabled(a: number): number;
export function __wbg_set_selectionoptions_selection_enabled(a: number, b: number): void;
export function __wbg_get_selectionoptions_selection_mode(a: number): number;
export function __wbg_set_selectionoptions_selection_mode(a: number, b: number): void;
export function __wbg_staticmappane_free(a: number): void;
export function __wbg_mappane_free(a: number): void;
export function mappane_get_name(a: number, b: number): void;
export function mappane_set_name(a: number, b: number, c: number): void;
export function __wbg_selectionoptions_free(a: number): void;
export function __wbg_theme_free(a: number): void;
export function theme_get_primary_color(a: number): number;
export function theme_set_primary_color(a: number, b: number): void;
export function theme_get_secondary_color(a: number): number;
export function theme_set_secondary_color(a: number, b: number): void;
export function theme_get_icon(a: number, b: number): void;
export function theme_set_icon(a: number, b: number, c: number): void;
export function __wbg_histogrampane_free(a: number): void;
export function histogrampane_get_name(a: number, b: number): void;
export function histogrampane_set_name(a: number, b: number, c: number): void;
export function __wbg_labels_free(a: number): void;
export function __wbg_scatterplotpane_free(a: number): void;
export function __wbg_linechartpane_free(a: number): void;
export function __wbg_piechartpane_free(a: number): void;
export function scatterplotpane_set_name(a: number, b: number, c: number): void;
export function linechartpane_set_name(a: number, b: number, c: number): void;
export function piechartpane_set_name(a: number, b: number, c: number): void;
export function scatterplotpane_get_name(a: number, b: number): void;
export function linechartpane_get_name(a: number, b: number): void;
export function piechartpane_get_name(a: number, b: number): void;
export function __wbg_set_linearlayout_direction(a: number, b: number): void;
export function __wbg_get_linearlayout_allow_overflow(a: number): number;
export function __wbg_set_linearlayout_allow_overflow(a: number, b: number): void;
export function __wbg_get_linearlayout_justify(a: number): number;
export function __wbg_set_linearlayout_justify(a: number, b: number): void;
export function __wbg_get_linearlayout_gap(a: number): number;
export function __wbg_set_linearlayout_gap(a: number, b: number): void;
export function __wbg_get_linearlayout_align(a: number): number;
export function __wbg_set_linearlayout_align(a: number, b: number): void;
export function __wbg_freelayout_free(a: number): void;
export function __wbg_get_freelayout_allow_overflow(a: number): number;
export function __wbg_set_freelayout_allow_overflow(a: number, b: number): void;
export function __wbg_gridlayout_free(a: number): void;
export function __wbg_page_free(a: number): void;
export function page_get_name(a: number, b: number): void;
export function page_set_name(a: number, b: number, c: number): void;
export function page_get_path(a: number, b: number): void;
export function page_set_path(a: number, b: number, c: number): void;
export function page_get_icon(a: number, b: number): void;
export function page_set_icon(a: number, b: number, c: number): void;
export function page_add_pane(a: number, b: number, c: number, d: number, e: number): void;
export function page_add_pane_before(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function page_add_pane_after(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function page_move_pane_to_position(a: number, b: number, c: number, d: number): void;
export function page_add_pane_at_position(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function page_remove_pane_at_position(a: number, b: number): void;
export function page_remove_pane(a: number, b: number, c: number): void;
export function __wbg_tablayout_free(a: number): void;
export function __wbg_linearlayout_free(a: number): void;
export function __wbg_get_linearlayout_direction(a: number): number;
export function __wbg_containerpane_free(a: number): void;
export function __wbg_controlspane_free(a: number): void;
export function __wbg_textpane_free(a: number): void;
export function textpane_get_content(a: number, b: number): void;
export function textpane_set_content(a: number, b: number, c: number): void;
export function textpane_get_name(a: number, b: number): void;
export function textpane_set_name(a: number, b: number, c: number): void;
export function textpane_get_font(a: number, b: number): void;
export function textpane_set_font(a: number, b: number, c: number): void;
export function textpane_get_background(a: number, b: number): void;
export function textpane_set_background(a: number, b: number, c: number): void;
export function paneposition_get_x_units(a: number, b: number): void;
export function paneposition_get_y_units(a: number, b: number): void;
export function paneposition_get_width_units(a: number, b: number): void;
export function paneposition_get_height_units(a: number, b: number): void;
export function paneposition_get_pad_units_left(a: number, b: number): void;
export function paneposition_get_pad_units_right(a: number, b: number): void;
export function paneposition_get_pad_units_top(a: number, b: number): void;
export function paneposition_get_pad_units_bottom(a: number, b: number): void;
export function __wbg_paneposition_free(a: number): void;
export function __wbg_get_paneposition_width(a: number): number;
export function __wbg_set_paneposition_width(a: number, b: number): void;
export function __wbg_get_paneposition_height(a: number): number;
export function __wbg_set_paneposition_height(a: number, b: number): void;
export function __wbg_get_paneposition_layer(a: number): number;
export function __wbg_set_paneposition_layer(a: number, b: number): void;
export function __wbg_get_paneposition_float(a: number): number;
export function __wbg_set_paneposition_float(a: number, b: number): void;
export function __wbg_get_paneposition_x(a: number, b: number): void;
export function __wbg_set_paneposition_x(a: number, b: number, c: number): void;
export function __wbg_get_paneposition_y(a: number, b: number): void;
export function __wbg_set_paneposition_y(a: number, b: number, c: number): void;
export function __wbg_get_paneposition_pad_left(a: number, b: number): void;
export function __wbg_set_paneposition_pad_left(a: number, b: number, c: number): void;
export function __wbg_get_paneposition_pad_right(a: number, b: number): void;
export function __wbg_set_paneposition_pad_right(a: number, b: number, c: number): void;
export function __wbg_get_paneposition_pad_top(a: number, b: number): void;
export function __wbg_set_paneposition_pad_top(a: number, b: number, c: number): void;
export function __wbg_get_paneposition_pad_bottom(a: number, b: number): void;
export function __wbg_set_paneposition_pad_bottom(a: number, b: number, c: number): void;
export function __wbg_aggregatestep_free(a: number): void;
export function __wbg_filterstep_free(a: number): void;
export function __wbg_columntransform_free(a: number): void;
export function __wbg_columntransformstep_free(a: number): void;
export function __wbg_joinstep_free(a: number): void;
export function __wbg_imputestep_free(a: number): void;
export function __wbg_aggregationsummary_free(a: number): void;
export function __wbg_datasettransform_free(a: number): void;
export function __wbg_metadata_free(a: number): void;
export function __wbg_app_free(a: number): void;
export function app_new_dash(): number;
export function app_get_pages(a: number): number;
export function app_set_pages(a: number, b: number): void;
export function app_get_panes(a: number): number;
export function app_set_panes(a: number, b: number): void;
export function app_get_theme(a: number): number;
export function app_set_theme(a: number, b: number): void;
export function app_get_datasets(a: number): number;
export function app_set_datasets(a: number, b: number): void;
export function app_get_name(a: number, b: number): void;
export function app_set_name(a: number, b: number, c: number): void;
export function app_get_description(a: number, b: number): void;
export function app_set_description(a: number, b: number, c: number): void;
export function app_get_created_at(a: number): number;
export function app_set_created_at(a: number, b: number): void;
export function app_from_js(a: number, b: number): void;
export function app_from_json(a: number, b: number, c: number): void;
export function app_is_valid(a: number): number;
export function app_to_js(a: number): number;
export function app_to_toml(a: number, b: number): void;
export function app_to_yaml(a: number, b: number): void;
export function __wbg_validationresult_free(a: number): void;
export function __wbg_get_validationresult_is_valid(a: number): number;
export function __wbg_set_validationresult_is_valid(a: number, b: number): void;
export function __wbg_cogdataset_free(a: number): void;
export function __wbg_arrowdataset_free(a: number): void;
export function __wbg_wasmcompute_free(a: number): void;
export function __wbg_maticoremotedataset_free(a: number): void;
export function __wbg_maticoapidataset_free(a: number): void;
export function maticoremotedataset_get_description(a: number, b: number): void;
export function maticoremotedataset_set_description(a: number, b: number, c: number): void;
export function maticoremotedataset_get_server_url(a: number, b: number): void;
export function maticoremotedataset_set_server_url(a: number, b: number, c: number): void;
export function maticoremotedataset_get_dataset_id(a: number, b: number): void;
export function maticoremotedataset_set_dataset_id(a: number, b: number, c: number): void;
export function __wbg_csvdataset_free(a: number): void;
export function csvdataset_get_name(a: number, b: number): void;
export function csvdataset_set_name(a: number, b: number, c: number): void;
export function maticoremotedataset_set_name(a: number, b: number, c: number): void;
export function geojsondataset_set_name(a: number, b: number, c: number): void;
export function __wbg_signeds3arrowdataset_free(a: number): void;
export function maticoremotedataset_get_name(a: number, b: number): void;
export function geojsondataset_get_name(a: number, b: number): void;
export function __wbg_geojsondataset_free(a: number): void;
export function __wbg_selectcontrol_free(a: number): void;
export function __wbg_rangecontrol_free(a: number): void;
export function __wbg_datetimesliderpane_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
