import { ContinuousChartSpaceProps } from "./ContinuousChartSpace.types";
export default function ContinuousChartspace({
  data,
  layers,
  xCol,
  tickFormatFunc,
  xAxis,
  xAxisPos,
  xLabel,
  xMax,
  xExtent,
  yCol,
  yAxis,
  yAxisPos,
  yLabel,
  yMax,
  yExtent,
  grid,
  width,
  height,
  margin,
  useBrush,
  onBrush,
  children,
  ...rest
}: ContinuousChartSpaceProps): JSX.Element | null;
